import { createTypes } from 'reduxsauce';

export default createTypes(`
    ADD_INGREDIENT
    REMOVE_INGREDIENT
    SET_INGREDIENTS
    FETCH_INGREDIENTS_FAILED

    PURCHASE_BURGER_START
    PURCHASE_BURGER_SUCCESS
    PURCHASE_BURGER_FAIL
    PURCHASE_INIT

    FETCH_ORDERS_START
    FETCH_ORDERS_SUCCESS
    FETCH_ORDERS_FAIL

    AUTH_START
    AUTH_SUCCESS
    AUTH_FAIL
    AUTH_LOGOUT

    SET_AUTH_REDIRECT_PATH
`);